name: Publish Docker Image

concurrency:
  group: publish-docker-image-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - "client/**"
      - "server/**"
      - "Dockerfile"

  workflow_dispatch:
    inputs:
      version:
        description: Docker image verzió tag (pl. 1.2.3)
        type: string
        required: true
      latest:
        description: Állítsa be a 'latest' taget is?
        type: boolean
        required: false
        default: false

jobs:
  server:
    name: Server
    uses: ./.github/workflows/reusable-test-and-build.yaml
    with:
      working-directory: ./server

  client:
    name: Client
    uses: ./.github/workflows/reusable-test-and-build.yaml
    with:
      working-directory: ./client

  build-and-push:
    name: Build Docker image and Publish
    needs:
      - server
      - client

    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
        name: Docker QEMU

      - uses: docker/setup-buildx-action@v3
        name: Docker Buildx

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/stremhu-source
          tags: |
            type=raw,value=dev,enable=${{ github.event_name != 'workflow_dispatch' && github.ref == 'refs/heads/main' }}
            type=raw,value=${{ inputs.version }},enable=${{ github.event_name == 'workflow_dispatch' && inputs.version != '' }}
            type=raw,value=latest,enable=${{ github.event_name == 'workflow_dispatch' && (inputs.latest == true || inputs.latest == 'true') }}

      - name: Compute version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ inputs.version }}" ]; then
            echo "value=v${{ inputs.version }}" >> "$GITHUB_OUTPUT"
          else
            echo "value=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and Publish
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            APP_VERSION=${{ steps.version.outputs.value }}
